# Utiliser une image Node.js
FROM node:20-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm ci --production

# Copier le reste des fichiers
COPY . .

# Construire l'application (Désactiver les erreurs CI)
RUN CI=false npm run build

# Exposer le port
ENV PORT=3000
EXPOSE 3000

# Commande de démarrage
CMD ["node", "dist/index.js"]
